volumes:
  geo-db-data:
services:
    redis:
      container_name: redis-db
      image: redis:latest
    app:
      container_name: main-app
      env_file:
        - develop.env
      image: app_drf:latest
      command: python manage.py runserver 0.0.0.0:8000
      depends_on:
        - redis
      ports:
      - 8000:8000
#    api-beat:
#      container_name: sheduler
#      image: app_drf:latest
#      command: celery -A forecast_app.tasks.app  beat --loglevel=info
#      depends_on:
#        - main-app
#    api-worker:
#      container_name: worker
#      image: app_drf:latest
#      command: celery -A celery_app worker --pool=solo --loglevel=info
#      depends_on:
#        - main-app



