version: "3.8"

services:
    redis:
      container_name: redis-db
      image: redis:latest
    main-app:
      container_name: main-app
      env_file:
        - develop.env
      image: app_drf:latest
      command: python manage.py runserver 0.0.0.0:8000
      depends_on:
        - redis
      ports:
      - 8000:8000
    api-beat:
      container_name: sheduler
      env_file:
        - develop.env
      image: app_drf:latest
      command: celery -A celery_app beat --loglevel=info
      depends_on:
        - main-app
    api-worker:
      container_name: worker
      env_file:
        - develop.env
      image: app_drf:latest
      command: celery -A celery_app worker --pool=solo --loglevel=info
      depends_on:
        - main-app



